package com.example.demo;
// Generated by Selenium IDE

import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;

public class DiaryTest {
    private static ApplicationManager appManager;
    private static final String LINUX_GECKODRIVER_PATH = "/home/melok/Downloads/geckodriver";
    private static final String WIN_GECKODRIVER_PATH = "C:\\Users\\User\\Downloads\\geckodriver.exe";


    public DiaryTest() {
        System.setProperty("webdriver.gecko.driver", WIN_GECKODRIVER_PATH);
    }

    @Before
    public void setUp() {
        appManager = ApplicationManager.getInstance();
    }

    @AfterClass
    public static void tearDown() {
        appManager.getDriver().quit();
    }

    @Test
    public void diary1() {
        appManager.getNavigationHelper().openHomePage(appManager.getDriver());
        appManager.getLoginHelper().login(appManager.getDriver(), appManager.getUser());
        appManager.getPostHelper().addPost(appManager.getDriver(), appManager.getPost1());

        System.out.println("=======\n===============\n==============\n============"+
                appManager.getDriver().findElement(By.className("dt")).getText());
        Assert.assertEquals(appManager.getPost1().getText(), appManager.getDriver().findElement(By.className("dt")).getText());
        appManager.getLogoutHelper().logout(appManager.getDriver());
    }

    @Test
    public void diary2() {
        appManager.getNavigationHelper().openHomePage(appManager.getDriver());
        appManager.getLoginHelper().login(appManager.getDriver(), appManager.getUser());
        appManager.getPostHelper().addPost(appManager.getDriver(), appManager.getPost2());
        System.out.println("=======\n===============\n==============\n============"+
                appManager.getDriver().findElement(By.className("dt")).getText());
        Assert.assertEquals(appManager.getPost2().getText(), appManager.getDriver().findElement(By.className("dt")).getText());
    }
}
