package com.example.demo;
// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

public class DiaryTest {
    ApplicationManager appManager;

    public DiaryTest() {
        System.setProperty("webdriver.gecko.driver", "/home/melok/Downloads/geckodriver");
    }

    @Before
    public void setUp() {
        appManager = new ApplicationManager();
    }

    @After
    public void tearDown() {
        appManager.getDriver().quit();
    }

    @Test
    public void diary1() {
        appManager.getNavigationHelper().openHomePage(appManager.getDriver());
        appManager.getLoginHelper().login(appManager.getDriver(), appManager.getUser());
        appManager.getPostHelper().addPost(appManager.getDriver(), appManager.getPost1());
    }

    @Test
    public void diary2() {
        appManager.getNavigationHelper().openHomePage(appManager.getDriver());
        appManager.getLoginHelper().login(appManager.getDriver(), appManager.getUser());
        appManager.getPostHelper().addPost(appManager.getDriver(), appManager.getPost2());
    }
}
